### PR TITLE
Add First Contributors

### PR DESCRIPTION
**Pull request by Roshanjossey**
First Contributors is a community that helps people with open source
 contributions

I have a project to help get beginners get started with contributing to open source projects, [First Contributions](https://github.com/Roshanjossey/first-contributions).

I maintains this slack community to continue engagement with users, help them contribute to other projects

### CODE REVIEW

**Comment by Roshanjossey** [comment]
@filipelinhares: I looked into the reason of build failure and learned that it's because of these links failing

>Issues :-(
>> Links 
>  1. [L14]  http://nodeslackers.io/ getaddrinfo: Name or service not known 
>  2. [L22]  http://slack.phalconphp.com Connection timed out - connect(2) for "slack.phalconphp.com" port 80 
>  3. [L27]  https://slashrocket.io/ getaddrinfo: Name or service not known 
>  4. [L30] 404 https://quokkaslack.herokuapp.com/  
>  5. [L40] 404 http://grupypr.herokuapp.com/

**Comment by filipelinhares** [comment]
Thanks for your contribution @Roshanjossey 😄 

Yeah. I need to clean the broken links. I'm merging your PR for now. Soon I make the tests pass.

**Comment by Roshanjossey** [comment]
@filipelinhares: Shall I submit another PR to remove broken links?

**Comment by filipelinhares** [comment]
i'll appreciate, @Roshanjossey 😄

**Pull request merged**
